name: App Release

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.16.1]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npx -p @semantic-release/exec -p semantic-release semantic-release
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
